config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      OrderMailer.with(order: @order).new_order_email.deliver_later
      OrderMailer.with(order: @order).order_confirmation_email.deliver_later

      flash[:success] = t('flash.order.success')
      redirect_to root_path, notice: 'Order was successfully sent'
    else
      flash.now[:error] = t('flash.order.error_html')
      render :new, notice: 'something went wrong'
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :address, :phone, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrdersMailboxer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Limelight&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<div class="flex-row d-flex justify-content-center m-1">
  <div class="card mt-1">
    <div class="card-body m-5">

      <%= simple_form_for(@order) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="row">
          <div class="col-xs-6 mr-5">
            <h3><%= f.input :name %></h3>
          </div>
          <div class="col-xs-6">
            <h3><%= f.input :email, placeholder: "Title of you order" %></h3>
          </div>
        </div>


        <div class="form-inputs">
            <h3><%= f.input :address %></h3>
        </div>


        <div class="form-inputs">
          <h3><%= f.input :phone %></h3>
        </div>

        <div class="form-inputs">
            <h3><%= f.input :message %></h3>
        </div>

        <br>
        <div class="form-actions">
          <%= f.button :submit, "save your order", class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="content">
  <h1>Place Your Order</h1>
  <p>
    <span id="banner-typed-text"></span>
  </p>
  <p><%= link_to "Place a Order", new_order_path, class: "btn btn-primary" %></p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>